### ISSUE TITLE
Add user specified resources to omics-run-analyzer CSV output file

### ISSUE THREAD

**Issue by sunilaladhi** [awslabs/amazon-omics-tools#30]
It would be good to include user requested CPUs/memory in the CSV file that gets generated by omics-run-analyzer. This additional info is needed as HealthOmics can choose an instance to closely map to the resources requested and those final resources can be different from what the user had specified.

**Comment by jwarnn** [comment]
@sunilaladhi if you are the creator of the workflow couldn't you reference the workflow definition to know the resources that were requested?

**Comment by mhemesath** [comment]
Posted PR here https://github.com/awslabs/amazon-omics-tools/pull/35

**Comment by markjschreiber** [comment]
Closed by #35
