### ISSUE TITLE
Update boto3 version in the requirements 

### ISSUE THREAD

**Issue by inbalzelig-ugi** [awslabs/amazon-omics-tools#44]
Hi, I want to use amazon-omics-tools>=0.4.0 in an environment with boto3>=1.34.135.
There is a dependency resolving issue: 

Error:
 × No solution found when resolving dependencies:
  ╰─▶ Because boto3>=1.34.136 depends on s3transfer>=0.10.0,<0.11.0 and only the following versions of boto3 are available:
          boto3<=1.34.136
          boto3==1.34.137
          boto3==1.34.138
          boto3==1.34.139
          boto3==1.34.140
          boto3==1.34.141
          boto3==1.34.142
          boto3==1.34.143
          boto3==1.34.144
          boto3==1.34.145
          boto3==1.34.146
          boto3==1.34.147
          boto3==1.34.148
          boto3==1.34.149
          boto3==1.34.150
          boto3==1.34.151
          boto3>=2.0.0
      we can conclude that boto3>=1.34.136 depends on s3transfer>=0.10.0,<0.11.0.
      And because amazon-omics-tools==0.4.0 depends on boto3>=1.28.83, we can conclude that amazon-omics-tools==0.4.0, any of:
          boto3<1.28.83
          boto3>=1.34.136
      , any of:
          s3transfer<0.10.0
          s3transfer>=0.11.0
       are incompatible.
      And because amazon-omics-tools==0.4.0 depends on s3transfer>=0.7.0,<0.8.0 and only amazon-omics-tools<=0.4.0 is available, we can conclude that
      amazon-omics-tools>=0.4.0 depends on boto3>=1.28.83,<1.34.136.
      And because you require boto3>=1.34.136 and amazon-omics-tools>=0.4.0, we can conclude that the requirements are unsatisfiable.
error: could not write production lockfile for project

Can the requirement be updated to use the latest boto3 version?

**Comment by inbalzelig-ugi** [comment]
Great news thanks! When will you release a new version so we can install it with pip?

[cid:841454ee-b973-4fe3-bb18-3610a83551e1]<https://www.ultimagenomics.com/>
Inbal Zelig​​​​
Software Engineer II
E:      ***@***.***
ultimagenomics.com<http://www.ultimagenomics.com/>
________________________________

**Comment by markjschreiber** [comment]
A new package version (v0.5.0) has been released to pip today.
