### ISSUE TITLE
run analyzer fails when workflow doesn't exist

### ISSUE THREAD

**Issue by avigailmo** [awslabs/amazon-omics-tools#75]
this line:
https://github.com/awslabs/amazon-omics-tools/blob/main/omics/cli/run_analyzer/__main__.py#L574

fails if the HealthOmics workflow was already deleted
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".venv/lib/python3.11/site-packages/omics/cli/run_analyzer/__main__.py", line 574, in <module>
    engine = omics.get_workflow(id=wfid)["engine"]
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetWorkflow operation: Workflow 3910207 not found

The workflow engine is [used](https://github.com/awslabs/amazon-omics-tools/blob/main/omics/cli/run_analyzer/__main__.py#L592) when `--write-config` flag is on (only in nextflow) but this failure happens also when it not used.

**Comment by markjschreiber** [comment]
Thanks for the bug report. Can you share the command line that produced the error? What flags (if any) were set on the command line? Was the tool running in Batch mode?

**Comment by avigailmo** [comment]
> Thanks for the bug report. Can you share the command line that produced the error? What flags (if any) were set on the command line? Was the tool running in Batch mode?

I get the error even when running the simplest command without any flag:
`python -m omics.cli.run_analyzer 3048418`
no batch mode

**Comment by markjschreiber** [comment]
@KevinSayers, this block https://github.com/awslabs/amazon-omics-tools/blob/main/omics/cli/run_analyzer/__main__.py#L574-L586 seems to be the place where the engine name is needed, however it looks like it is only needed when attempting to write a config file. Could you refactor so that this is only done when the config flag is set?
