### ISSUE TITLE
run analyzer fails on run with cache

### ISSUE THREAD

**Issue by avigailmo** [awslabs/amazon-omics-tools#77]
When I try to run the  run_analyzer on a run that configured to run with run_cache (no matter if there were cache hits or not) it fails with the following error:
File "omics/cli/run_analyzer/__main__.py", line 460, in <module>
    resources = get_run_resources(logs, runs[0])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "omics/cli/run_analyzer/__main__.py", line 257, in get_run_resources
    return sorted(resources, key=lambda x: x.get("creationTime"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'str'

example to such run: arn:aws:omics:us-east-1:891377049375:run/9748207
I run the command without any flag: 
`python -m omics.cli.run_analyzer 9748207`

**Comment by markjschreiber** [comment]
Thanks for reporting this. Looks like this line of code needs to provide a default time if the `creationTime` doesn't exist so that the results can be sorted.
https://github.com/awslabs/amazon-omics-tools/blob/main/omics/cli/run_analyzer/__main__.py#L257C5-L257C66

I think in other parts of the code we have used the arbitrary default date of 1970-01-01

**Comment by markjschreiber** [comment]
@avigailmo can you try the fix in #78 and let me know if that works for you?

**Comment by avigailmo** [comment]
> @avigailmo can you try the fix in #78 and let me know if that works for you?

My try failed due the the [engine issue](https://github.com/awslabs/amazon-omics-tools/issues/75) I've raised: because the workflow doesn't exist anymore

I tried to set the engine to "WDL" hardcoded

then I got this for the run that ran with cache:

>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/Users/avigailmoldovan/dev/amazon-omics-tools/omics/cli/run_analyzer/__main__.py", line 579, in <module>
>     "cpus": metrics["recommendedCpus"],
>             ~~~~~~~^^^^^^^^^^^^^^^^^^^
> KeyError: 'recommendedCpus'

**Comment by avigailmo** [comment]
yes, these's manifest log
will send it to you by email
